[package]
name = "remotelink_client"
version = "0.1.0"
edition = "2021"

[dependencies]
remotelink = { path = ".." }
anyhow = "1.0"
bincode = "1.3"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
